name: Publish Package to npmjs

on:
  push:
    tags:
    - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
